stages:
  - test
  - info
api_test:
  stage: test
  image:
    name: node:latest
  script:
    - npm install
    - npm test
  artifacts:
    when: always
    paths:
      - ./temp/result.html
    expire_in: 2 week
